### ISSUE TITLE
Please consider to add gvfs permission

### ISSUE THREAD

**Issue by waldhef** [fejfighter/pgtk-emacs-flatpak#6]
Hello,
I've tried to edit a file which I've mounted with Nautilus on my Samba share and got out of luck until I figured out I need to permit  gvfs access.

So I started Emacs with: `flatpak --filesystem=xdg-run/gvfs run org.gnu.emacs-pgtk` and could successful edit my file.

Note: although the Flatpak documentation (https://docs.flatpak.org/en/latest/sandbox-permissions.html#gvfs-access) say:

> Typical GNOME and GTK applications should use:
> 
> `--talk-name=org.gtk.vfs.*`
> `--filesystem=xdg-run/gvfsd`
> 
> Typical non-GNOME and non-GTK applications should use:
> 
> `--filesystem=xdg-run/gvfs`

But `flatpak --talk-name=org.gtk.vfs.* --filesystem=xdg-run/gvfsd run org.gnu.emacs-pgtk` didn't work for me.

By the way, I want to say you a big thanks for your work, everything else works great so far :+1:

**Comment by fejfighter** [comment]
Hi @waldhef, 

Sorry for a bit of a delay in getting back to you,

this should be taken care of in `83a5e1a`, please let me know if that works.

The documentation slightly over simplifies the gtk v non-gtk bit, it's really about using g-objects and libraries which emacs doesn't use, but most normal gtk programs likely would.

Going to close this for now, but re-open if that's not enough

**Comment by waldhef** [comment]
I can confirm the latest reversion 70abe2a works fine for me. I could successfully open a file on my Samba share, which I mounted with Nautilus. Thank you very much! :+1:
